version: "3"

services:
  eureka-server:
    image: guilhermejr/sistema-eureka-server
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"

networks:
  default:
    external:
      name: rede